In [15]:
# imports
import pandas as pd
import numpy as np
import os
pd.set_option('display.max_columns', None)

In [30]:
# load each file into a dict of dataframes
data = {}
file_names = os.listdir('data/afl')
for file_name in file_names:
    with open('data/afl/' + file_name) as f:
        data[file_name[:-4]] = pd.read_csv(f)
        # rename the ID column to Player ID
        data[file_name[:-4]].rename(columns={'ID': 'Player ID'}, inplace=True)
        # snake case the column names
        data[file_name[:-4]].columns = data[file_name[:-4]].columns.str.lower().str.replace(' ', '_')
        # add year column to each dataframe
        data[file_name[:-4]]['year'] = file_name[0:4]

In [32]:
data['2023_stats'].head()

,player,player_id,team,opponent,round,kicks,marks,hand_balls,disp,goals,behinds,hit_outs,tackles,rebounds,inside_50,clearances,clangers,frees_for,frees_against,brownlow,contested_possessions,uncontested_possessions,contested_marks,marks_inside_50,one_percenters,bounces,goal_assists,%_time_played,year
0,Liam Baker,12661,RI,CA,1,10,5,5,15,0,0,0,1,2,1,0,2,2,2,0,4,10,0,0,0,1,0,84,2023
1,Noah Balta,12686,RI,CA,1,6,3,2,8,0,0,0,1,4,1,0,2,0,0,0,5,2,2,0,2,0,0,87,2023
2,Shai Bolton,12535,RI,CA,1,15,6,3,18,1,1,0,4,0,7,3,5,2,2,3,8,12,1,2,1,1,1,88,2023
3,Nathan Broad,12456,RI,CA,1,11,7,2,13,0,0,0,3,2,2,1,2,0,0,0,2,11,1,0,3,0,0,90,2023
4,Trent Cotchin,11666,RI,CA,1,9,3,9,18,0,0,0,3,3,3,4,5,0,3,0,11,7,0,0,2,0,0,67,2023

In [34]:
# get distinct Teams from data['2023_stats]
teams = data['2023_stats']['team'].unique()
teams

array(['RI', 'CA', 'CW', 'GE', 'NM', 'WC', 'PA', 'BL', 'SY', 'GC', 'ME',
       'WB', 'AD', 'GW', 'HW', 'ES', 'SK', 'FR'], dtype=object)